# Generated by Django 3.2.22 on 2023-11-03 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('DIRSELL', 'Direct Sell'), ('AUCTION', 'Auction'), ('TRADE', 'Trade'), ('SOLD', 'Sold')], default='Direct Sell', max_length=20),
        ),
    ]
