# Generated by Django 3.2.22 on 2023-11-06 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_bought_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('MOBILES', 'Mobiles'), ('CLOTHING', 'Clothing'), ('BOOKS', 'Books'), ('VEHICLES', 'Vehicles')], max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('DIRSELL', 'Direct Sell'), ('AUCTION', 'Auction')], default='Direct Sell', max_length=20),
        ),
    ]
