# Generated by Django 3.2.22 on 2023-11-04 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_status'),
        ('direct_sell', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directsellproduct',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
    ]
