# Generated by Django 3.2.22 on 2023-11-06 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direct_sell', '0002_alter_directsellproduct_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directsellproduct',
            name='price',
            field=models.IntegerField(),
        ),
    ]
