# Generated by Django 3.2.22 on 2023-11-07 02:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bid', '0002_alter_auctionitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionitem',
            name='highest_bidder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
